### ISSUE TITLE
Accuracy problem with Subsurf Modifier

### ISSUE THREAD

**Issue by piacenti** [Antonioya/blender#51]
When using Subsurf modifier the measurements don't take into account what is being displayed but rather it uses the original form of the mesh. Also when the modifier is applied all measurements get messed up (not a big deal most of the time since I usually apply them while exporting).

**Comment by Antonioya** [comment]
This is not a bug. When you add a subdivision, the vertex is moved on screen, but internally remains in the same position. When you apply, the vertex number and order changes, so the measure is not valid because the measure uses the index of the vertex. This cannot be fixed.

If you want add a measure to subdivide mesh, create the measure after apply the modifier, but never before or you will get wrong results.
